//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int num_emp { get; set; }
        public string nom_emp { get; set; }
        public string rut_emp { get; set; }
        public string dir_emp { get; set; }
        public string tel_emp { get; set; }
        public string cor_emp { get; set; }
        public string idc_emp { get; set; }
    }
}
